/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taxi;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Daniel
 */
public class RealizarChamado extends javax.swing.JFrame {

    static ArrayList<Chamado> listaChamados;
    String botao;
    
    public RealizarChamado() {
        initComponents();
        
        listaChamados = new ArrayList();
        
        
        formatarCampo();
        
        btnNovo.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnPesquisar.setEnabled(true);
        btnOK.setEnabled(false);
        
        txtID.setEnabled(false);
        txtDestino.setEnabled(false);
        txtOrigem.setEnabled(false);
        ftxtData.setEnabled(false);
        comCliente.setEnabled(false);
        
    }
    
    public void carregarTabelaChamados() {
    DefaultTableModel modelo = new DefaultTableModel(new Object[] {"ID","Cliente","Data","Origem","Destino"},0);

    for(int i=0; i<listaChamados.size();i++){
        Object linha[] = new Object[]{listaChamados.get(i).getId(),
                                      listaChamados.get(i).getCliente().getNome(),
                                      listaChamados.get(i).getData(),
                                      listaChamados.get(i).getOrigem(),
                                      listaChamados.get(i).getDestino()};
        modelo.addRow(linha);
    }
    tabChamados.setModel(modelo);
}
    public void carregarClientes(){
        comCliente.removeAllItems();
        
        comCliente.addItem("Selecione um Cliente");
        
        for(int i=0;i<CadastroCliente.listaClientes.size();i++) {
            comCliente.addItem(CadastroCliente.listaClientes.get(i).getNome());
        }
    }
    
    public void formatarCampo() {     
            try {
                MaskFormatter mask;
                mask = new MaskFormatter("##\\##\\####");
                mask.install(ftxtData);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Erro em formatar", "Aviso", JOptionPane.ERROR_MESSAGE);
            }
        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnChamado = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        comCliente = new javax.swing.JComboBox<>();
        lblData = new javax.swing.JLabel();
        ftxtData = new javax.swing.JFormattedTextField();
        lblDestino = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        lblOrigem = new javax.swing.JLabel();
        txtOrigem = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        spnTabela = new javax.swing.JScrollPane();
        tabChamados = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnChamado.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Chamado"));

        lblID.setText("ID:");

        lblCliente.setText("Cliente:");

        comCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Cliente" }));
        comCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comClienteActionPerformed(evt);
            }
        });

        lblData.setText("Data:");

        ftxtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtDataActionPerformed(evt);
            }
        });

        lblDestino.setText("Destino:");

        lblOrigem.setText("Origem:");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnChamadoLayout = new javax.swing.GroupLayout(pnChamado);
        pnChamado.setLayout(pnChamadoLayout);
        pnChamadoLayout.setHorizontalGroup(
            pnChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChamadoLayout.createSequentialGroup()
                .addGroup(pnChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChamadoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(pnChamadoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnChamadoLayout.createSequentialGroup()
                                .addComponent(txtID)
                                .addGap(55, 55, 55))
                            .addGroup(pnChamadoLayout.createSequentialGroup()
                                .addComponent(ftxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)))
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGroup(pnChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnChamadoLayout.createSequentialGroup()
                        .addComponent(lblDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnChamadoLayout.createSequentialGroup()
                        .addComponent(lblOrigem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisar))
                .addGap(35, 35, 35))
        );
        pnChamadoLayout.setVerticalGroup(
            pnChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChamadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChamadoLayout.createSequentialGroup()
                        .addGroup(pnChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(lblOrigem)
                            .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnChamadoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDestino)))
                            .addGroup(pnChamadoLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblData))))
                    .addGroup(pnChamadoLayout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(pnChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOK))))
                .addGap(18, 18, 18)
                .addGroup(pnChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(comCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tabChamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Data", "Origem", "Destino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabChamados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabChamadosMouseClicked(evt);
            }
        });
        spnTabela.setViewportView(tabChamados);
        if (tabChamados.getColumnModel().getColumnCount() > 0) {
            tabChamados.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvar)
                                .addGap(17, 17, 17)
                                .addComponent(btnEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir)))))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addComponent(spnTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftxtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtDataActionPerformed

    private void comClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comClienteActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        botao = "novo";

        btnNovo.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnPesquisar.setEnabled(true);
        btnOK.setEnabled(false);
        comCliente.removeAllItems();
        comCliente.addItem("Selecione um Cliente");
        
        txtID.setEnabled(true);
        txtDestino.setEnabled(true);
        txtOrigem.setEnabled(true);
        ftxtData.setEnabled(true);
        comCliente.setEnabled(true);
        formatarCampo();
        
        txtID.setText("");
        txtDestino.setText("");
        txtOrigem.setText("");
        ftxtData.setText("");
        
        carregarClientes();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnNovo.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnPesquisar.setEnabled(true);
        btnOK.setEnabled(false);
        formatarCampo();
        
        txtID.setEnabled(false);
        txtDestino.setEnabled(false);
        txtOrigem.setEnabled(false);
        ftxtData.setEnabled(false);
        comCliente.setEnabled(false);
        comCliente.removeAllItems();
        comCliente.addItem("Selecione um Cliente");

        txtID.setText("");
        txtDestino.setText("");
        txtOrigem.setText("");
        ftxtData.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        int index = comCliente.getSelectedIndex();
                
        if (txtID.getText().equals("") || txtDestino.getText().equals("") || txtOrigem.getText().equals("") || ftxtData.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha os campos", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if (index==0) {
            JOptionPane.showMessageDialog(null, "Você deve selecionar um cliente", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else if (ftxtData.getText().trim().length()<10){
            JOptionPane.showMessageDialog(null, "A data deve estar no formato dd\\mm\\aaaa", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {

            int id = Integer.parseInt(txtID.getText());
            String data = ftxtData.getText();
            String origem = txtOrigem.getText();
            String destino = txtDestino.getText();

            if (botao.equals("novo")) {

                Chamado chamado = new Chamado(id,data,origem,destino);

                chamado.setCliente(CadastroCliente.listaClientes.get(index-1));
                
                listaChamados.add(chamado);

                CadastroCliente.listaClientes.get(index-1).criarChamado(chamado);
                
                JOptionPane.showMessageDialog(null, "Chamado realizado com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } else if (botao.equals("editar")) {
                int i = tabChamados.getSelectedRow();

                listaChamados.get(i).setId(id);
                listaChamados.get(i).setData(data);
                listaChamados.get(i).setOrigem(origem);
                listaChamados.get(i).setDestino(destino);
                listaChamados.get(i).setCliente(CadastroCliente.listaClientes.get(index-1));
            }

            carregarTabelaChamados();

            btnNovo.setEnabled(true);
            btnCancelar.setEnabled(true);
            btnSalvar.setEnabled(true);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnPesquisar.setEnabled(true);
            btnOK.setEnabled(false);
            formatarCampo();

            txtID.setEnabled(false);
            txtDestino.setEnabled(false);
            txtOrigem.setEnabled(false);
            ftxtData.setEnabled(false);
            comCliente.setEnabled(false);

            txtID.setText("");
            txtDestino.setText("");
            txtOrigem.setText("");
            ftxtData.setText("");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        botao = "editar";

        btnNovo.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnPesquisar.setEnabled(true);
        btnOK.setEnabled(false);
        
        
        txtID.setEnabled(true);
        txtDestino.setEnabled(true);
        txtOrigem.setEnabled(true);
        ftxtData.setEnabled(true);
        comCliente.setEnabled(true);

        formatarCampo();
        txtID.requestFocus();
        carregarClientes();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int index = tabChamados.getSelectedRow();
        

        if (index>=0 && index<listaChamados.size()) {
            listaChamados.remove(index);
        }
        carregarTabelaChamados();

        btnNovo.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnPesquisar.setEnabled(true);
        btnOK.setEnabled(false);
        comCliente.removeAllItems();
        comCliente.addItem("Selecione um Cliente");
        
        txtID.setEnabled(false);
        txtDestino.setEnabled(false);
        txtOrigem.setEnabled(false);
        ftxtData.setEnabled(false);
        comCliente.setEnabled(false);
        formatarCampo();

        txtID.setText("");
        txtDestino.setText("");
        txtOrigem.setText("");
        ftxtData.setText("");

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
      
        if (listaChamados.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não há chamados realizados!", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {

            txtID.setText("");
            txtDestino.setText("");
            txtOrigem.setText("");
            ftxtData.setText("");

            btnNovo.setEnabled(false);
            btnCancelar.setEnabled(true);
            btnSalvar.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnPesquisar.setEnabled(false);
            btnOK.setEnabled(true);
            comCliente.removeAllItems();
            comCliente.addItem("Selecione um Cliente");
            formatarCampo();

            txtID.setEnabled(false);
            txtDestino.setEnabled(false);
            txtOrigem.setEnabled(false);
            ftxtData.setEnabled(true);
            comCliente.setEnabled(false);

            ftxtData.requestFocus();
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (ftxtData.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "A data deve ser informada!", "Aviso", JOptionPane.ERROR_MESSAGE);
        }else{
            Chamado cha;
            String datai = ftxtData.getText();
            Cliente cliente = new Cliente();
            String id = "",data = "",origem = "",destino = "";

            for (int i=0;i<listaChamados.size();i++) {
                cha = listaChamados.get(i);

                if (datai.equals(cha.getData())){
                    id = String.valueOf(cha.getId());
                    data = cha.getData();
                    origem = cha.getOrigem();
                    destino = cha.getDestino();
                    cliente = cha.getCliente();
                }
            }

            if (data.equals("")) {
                JOptionPane.showMessageDialog(null, "Não ocorreu nenhum chamado nessa data.", "Aviso", JOptionPane.ERROR_MESSAGE);
                txtID.setText(id);
                ftxtData.setText(data);
                txtOrigem.setText(origem);
                txtDestino.setText(destino);
                
            }else{
                txtID.setText(id);
                ftxtData.setText(data);
                txtOrigem.setText(origem);
                txtDestino.setText(destino);
            }

            ftxtData.selectAll();
            ftxtData.requestFocus();
            btnNovo.setEnabled(false);
            btnCancelar.setEnabled(true);
            btnSalvar.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnPesquisar.setEnabled(true);
            btnOK.setEnabled(true);
            formatarCampo();
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void tabChamadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabChamadosMouseClicked
        if (listaChamados.isEmpty()) {
        } else {
            int i = tabChamados.getSelectedRow();

            if (i>=0 && i<listaChamados.size()) {
                Chamado cha = listaChamados.get(i);
                txtID.setText(String.valueOf(cha.getId()));
                ftxtData.setText(cha.getData());
                txtOrigem.setText(cha.getOrigem());
                txtDestino.setText(cha.getDestino());

            }
            btnNovo.setEnabled(true);
            btnCancelar.setEnabled(true);
            btnSalvar.setEnabled(false);
            btnEditar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnOK.setEnabled(false);

            txtID.setEnabled(false);
            txtDestino.setEnabled(false);
            txtOrigem.setEnabled(false);
            ftxtData.setEnabled(false);
            comCliente.setEnabled(false);
            
        }
    }//GEN-LAST:event_tabChamadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarChamado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comCliente;
    private javax.swing.JFormattedTextField ftxtData;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblOrigem;
    private javax.swing.JPanel pnChamado;
    private javax.swing.JScrollPane spnTabela;
    private javax.swing.JTable tabChamados;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtOrigem;
    // End of variables declaration//GEN-END:variables
}
